/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminSalonsRouteImport } from './routes/admin.salons'
import { Route as BusinessScheduleRouteImport } from './routes/business.schedule'
import { Route as BusinessServicesRouteImport } from './routes/business.services'
import { Route as BusinessStaffRouteImport } from './routes/business.staff'
import { Route as SalonSalonIdRouteImport } from './routes/salon.$salonId'
import { Route as SalonSalonIdBookRouteImport } from './routes/salon.$salonId.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsRoute = AdminSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessScheduleRoute = BusinessScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessServicesRoute = BusinessServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessStaffRoute = BusinessStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BusinessRoute,
} as any)
const SalonSalonIdRoute = SalonSalonIdRouteImport.update({
  id: '/salon/$salonId',
  path: '/salon/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonSalonIdBookRoute = SalonSalonIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SalonSalonIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/business': typeof BusinessRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/salons': typeof AdminSalonsRoute
  '/business/schedule': typeof BusinessScheduleRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/staff': typeof BusinessStaffRoute
  '/salon/$salonId': typeof SalonSalonIdRouteWithChildren
  '/salon/$salonId/book': typeof SalonSalonIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/business': typeof BusinessRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/salons': typeof AdminSalonsRoute
  '/business/schedule': typeof BusinessScheduleRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/staff': typeof BusinessStaffRoute
  '/salon/$salonId': typeof SalonSalonIdRouteWithChildren
  '/salon/$salonId/book': typeof SalonSalonIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/business': typeof BusinessRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/salons': typeof AdminSalonsRoute
  '/business/schedule': typeof BusinessScheduleRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/staff': typeof BusinessStaffRoute
  '/salon/$salonId': typeof SalonSalonIdRouteWithChildren
  '/salon/$salonId/book': typeof SalonSalonIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/business'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/salons'
    | '/business/schedule'
    | '/business/services'
    | '/business/staff'
    | '/salon/$salonId'
    | '/salon/$salonId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/business'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/salons'
    | '/business/schedule'
    | '/business/services'
    | '/business/staff'
    | '/salon/$salonId'
    | '/salon/$salonId/book'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/business'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/salons'
    | '/business/schedule'
    | '/business/services'
    | '/business/staff'
    | '/salon/$salonId'
    | '/salon/$salonId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalonSalonIdRoute: typeof SalonSalonIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salons': {
      id: '/admin/salons'
      path: '/salons'
      fullPath: '/admin/salons'
      preLoaderRoute: typeof AdminSalonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/schedule': {
      id: '/business/schedule'
      path: '/schedule'
      fullPath: '/business/schedule'
      preLoaderRoute: typeof BusinessScheduleRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/services': {
      id: '/business/services'
      path: '/services'
      fullPath: '/business/services'
      preLoaderRoute: typeof BusinessServicesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/staff': {
      id: '/business/staff'
      path: '/staff'
      fullPath: '/business/staff'
      preLoaderRoute: typeof BusinessStaffRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/salon/$salonId': {
      id: '/salon/$salonId'
      path: '/salon/$salonId'
      fullPath: '/salon/$salonId'
      preLoaderRoute: typeof SalonSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$salonId/book': {
      id: '/salon/$salonId/book'
      path: '/book'
      fullPath: '/salon/$salonId/book'
      preLoaderRoute: typeof SalonSalonIdBookRouteImport
      parentRoute: typeof SalonSalonIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminSalonsRoute: typeof AdminSalonsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminSalonsRoute: AdminSalonsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessRouteChildren {
  BusinessScheduleRoute: typeof BusinessScheduleRoute
  BusinessServicesRoute: typeof BusinessServicesRoute
  BusinessStaffRoute: typeof BusinessStaffRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessScheduleRoute: BusinessScheduleRoute,
  BusinessServicesRoute: BusinessServicesRoute,
  BusinessStaffRoute: BusinessStaffRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface SalonSalonIdRouteChildren {
  SalonSalonIdBookRoute: typeof SalonSalonIdBookRoute
}

const SalonSalonIdRouteChildren: SalonSalonIdRouteChildren = {
  SalonSalonIdBookRoute: SalonSalonIdBookRoute,
}

const SalonSalonIdRouteWithChildren = SalonSalonIdRoute._addFileChildren(
  SalonSalonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  BusinessRoute: BusinessRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalonSalonIdRoute: SalonSalonIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
